export const AccessCardCommunity = {
  ACCESS_CARD_COMMUNITY: 'ACCESS_CARD_COMMUNITY',
  ACCESS_CARD_COMMUNITY_LOADER: 'ACCESS_CARD_COMMUNITY_LOADER',
  ACCESS_CARD_COMMUNITY_SUCCESS: 'ACCESS_CARD_COMMUNITY_SUCCESS',
  ACCESS_CARD_COMMUNITY_ERROR: 'ACCESS_CARD_COMMUNITY_ERROR',
};
