export const AccessCardParkingBay = {
  ACCESS_CARD_PARKING_BAY: 'ACCESS_CARD_PARKING_BAY',
  ACCESS_CARD_PARKING_BAY_LOADER: 'ACCESS_CARD_PARKING_BAY_LOADER',
  ACCESS_CARD_PARKING_BAY_SUCCESS: 'ACCESS_CARD_PARKING_BAY_SUCCESS',
  ACCESS_CARD_PARKING_BAY_ERROR: 'ACCESS_CARD_PARKING_BAY_ERROR',
};
