export const AccountRenewalListActionTypes = {
    ACCOUNT_RENEWAL_LIST: 'ACCOUNT_RENEWAL_LIST',
    ACCOUNT_RENEWAL_LIST_LOADER: 'ACCOUNT_RENEWAL_LIST_LOADER',
    ACCOUNT_RENEWAL_LIST_SUCCESS: 'ACCOUNT_RENEWAL_LIST_SUCCESS',
    ACCOUNT_RENEWAL_LIST_ERROR: 'ACCOUNT_RENEWAL_LIST_ERROR',
  };