export const ActionTypes = {
    SAMPLE_REDUCER: "SAMPLE_REDUCER",
    SAMPLE_REDUCER_LOADER: "SAMPLE_REDUCER_LOADER",
    SAMPLE_REDUCER_SUCCESS: "SAMPLE_REDUCER_SUCCESS",
    SAMPLE_REDUCER_ERROR: "SAMPLE_REDUCER_ERROR",
};