export const AmenitiesListActionTypes = {
  AMENITIES_LIST: 'AMENITIES_LIST',
  AMENITIES_LIST_LOADER: 'REGISTRATION_LOADER',
  AMENITIES_LIST_SUCCESS: 'REGISTRATION_SUCCESS',
  AMENITIES_LIST_ERROR: 'REGISTRATION_ERROR',
};
