export const BookingSlotsActionTypes = {
  BOOKING_SLOTS: 'BOOKING_SLOTS',
  BOOKING_SLOTS_LOADER: 'BOOKING_SLOTS_LOADER',
  BOOKING_SLOTS_SUCCESS: 'BOOKING_SLOTS_SUCCESS',
  BOOKING_SLOTS_ERROR: 'BOOKING_SLOTS_ERROR',
};
