export const CatalogueWholeCommunityActionTypes = {
  CATALOGUE_WHOLE_COMMUNITY: 'CATALOGUE_WHOLE_COMMUNITY',
  CATALOGUE_WHOLE_COMMUNITY_LOADER: 'CATALOGUE_WHOLE_COMMUNITY_LOADER',
  CATALOGUE_WHOLE_COMMUNITY_SUCCESS: 'CATALOGUE_WHOLE_COMMUNITY_SUCCESS',
  CATALOGUE_WHOLE_COMMUNITY_ERROR: 'CATALOGUE_WHOLE_COMMUNITY_ERROR',
};
