export const CatalogueMasterCommunityActionTypes = {
  CATALOGUE_MASTER_COMMUNITY: 'CATALOGUE_MASTER_COMMUNITY',
  CATALOGUE_MASTER_COMMUNITY_LOADER: 'CATALOGUE_MASTER_COMMUNITY_LOADER',
  CATALOGUE_MASTER_COMMUNITYLIST_SUCCESS: 'CATALOGUE_MASTER_COMMUNITY__SUCCESS',
  CATALOGUE_MASTER_COMMUNITYLIST_ERROR: 'CATALOGUE_MASTER_COMMUNITY_ERROR',
};
