export const CatalogueUnitCommunityActionTypes = {
  CATALOGUE_COMMUNITY: 'CATALOGUE_COMMUNITY',
  CATALOGUE_COMMUNITY_LOADER: 'CATALOGUE_COMMUNITY_LOADER',
  CATALOGUE_COMMUNITY_SUCCESS: 'CATALOGUE_COMMUNITY__SUCCESS',
  CATALOGUE_COMMUNITY_ERROR: 'CATALOGUE_COMMUNITY_ERROR',
};
