export const ChangePasswordOtpGenActionTypes = {
    CHANGEPASSWORDOTPGEN: "CHANGEPASSWORDOTPGEN",
    CHANGEPASSWORDOTPGEN_LOADER: "CHANGEPASSWORDOTPGEN_LOADER",
    CHANGEPASSWORDOTPGEN_SUCCESS: "CHANGEPASSWORDOTPGEN__SUCCESS",
    CHANGEPASSWORDOTPGEN_ERROR: "CHANGEPASSWORDOTPGEN_ERROR",
};