export const CommonMasterCommunityActionTypes = {
    MASTER_COMMUNITY: "COMMON_MASTER_COMMUNITY",
    MASTER_COMMUNITY_LOADER: "COMMON_MASTER_COMMUNITY_LOADER",
    MASTER_COMMUNITY_SUCCESS: "COMMON_MASTER_COMMUNITY_SUCCESS",
    MASTER_COMMUNITY_ERROR: "COMMON_MASTER_COMMUNITY_ERROR",
    MASTER_COMMUNITY_RESET: "COMMON_MASTER_COMMUNITY_RESET",
};