export const CommonTowerActionTypes = {
    TOWER: "COMMON_TOWER",
    TOWER_LOADER: "COMMON_TOWER_LOADER",
    TOWER_SUCCESS: "COMMON_TOWER_SUCCESS",
    TOWER_ERROR: "COMMON_TOWER_ERROR",
    TOWER_RESET: "COMMON_TOWER_RESET",
};