export const CommonUnitDetailActionTypes = {
    UNIT_DETAIL: "UNIT_DETAIL",
    UNIT_DETAIL_LOADER: "UNIT_DETAIL_LOADER",
    UNIT_DETAIL_SUCCESS: "UNIT_DETAIL_SUCCESS",
    UNIT_DETAIL_ERROR: "UNIT_DETAIL_ERROR",
    UNIT_DETAIL_RESET: "UNIT_DETAIL_RESET",
};