export const CommonCommunityActionTypes = {
    COMMUNITY: "COMMON_COMMUNITY",
    COMMUNITY_LOADER: "COMMON_COMMUNITY_LOADER",
    COMMUNITY_SUCCESS: "COMMON_COMMUNITY_SUCCESS",
    COMMUNITY_ERROR: "COMMON_COMMUNITY_ERROR",
    COMMUNITY_RESET: "COMMON_COMMUNITY_RESET",
};