export const CompanyUpdateActionTypes = {
    COMPANY_UPDATE: 'COMPANY_UPDATE',
    COMPANY_UPDATE_LOADER: 'COMPANY_UPDATE_LOADER',
    COMPANY_UPDATE_SUCCESS: 'COMPANY_UPDATE_SUCCESS',
    COMPANY_UPDATE_ERROR: 'COMPANY_UPDATE_ERROR',
    COMPANY_UPDATE_RESET: 'COMPANY_UPDATE_RESET',
  };