export const CompanyRenewalCreateActionTypes = {
    COMPANY_RENEWAL_CREATE: 'COMPANY_RENEWAL_CREATE',
    COMPANY_RENEWAL_CREATE_LOADER: 'COMPANY_RENEWAL_CREATE_LOADER',
    COMPANY_RENEWAL_CREATE_SUCCESS: 'COMPANY_RENEWAL_CREATE_SUCCESS',
    COMPANY_RENEWAL_CREATE_ERROR: 'COMPANY_RENEWAL_CREATE_ERROR',
    COMPANY_RENEWAL_CREATE_RESET: 'COMPANY_RENEWAL_CREATE_RESET',
  };