export const CompanyCreateActionTypes = {
    COMPANY_CREATE: 'COMPANY_CREATE',
    COMPANY_CREATE_LOADER: 'COMPANY_CREATE_LOADER',
    COMPANY_CREATE_SUCCESS: 'COMPANY_CREATE_SUCCESS',
    COMPANY_CREATE_ERROR: 'COMPANY_CREATE_ERROR',
    COMPANY_CREATE_RESET: 'COMPANY_CREATE_RESET',
  };
  