export const DefaultPropertyActionTypes = {
    DEFAULT_PROPERTY: 'DEFAULT_PROPERTY',
    DEFAULT_PROPERTY_LOADER: 'DEFAULT_PROPERTY_LOADER',
    DEFAULT_PROPERTY_SUCCESS: 'DEFAULT_PROPERTY_SUCCESS',
    DEFAULT_PROPERTY_ERROR: 'DEFAULT_PROPERTY_ERROR',
  };