export const FilterUnitsActionTypes = {
  FILTER_UNITS: 'FILTER_UNITS',
  FILTER_UNITS_LOADER: 'FILTER_UNITS_LOADER',
  FILTER_UNITS_SUCCESS: 'FILTER_UNITS_SUCCESS',
  FILTER_UNITS_ERROR: 'FILTER_UNITS_ERROR',
};
