export const ForgotPasswordOtpActionTypes = {
    FORGOTPASSWORDOTP: "FORGOTPASSWORDOTP",
    FORGOTPASSWORDOTP_LOADER: "FORGOTPASSWORDOTP_LOADER",
    FORGOTPASSWORDOTP_SUCCESS: "FORGOTPASSWORDOTP__SUCCESS",
    FORGOTPASSWORDOTP_ERROR: "FORGOTPASSWORDOTP_ERROR",
};