export const ForgotPasswordActionTypes = {
    FORGOTPASSWORD: "FORGOTPASSWORD",
    FORGOTPASSWORD_LOADER: "FORGOTPASSWORD_LOADER",
    FORGOTPASSWORD_SUCCESS: "FORGOTPASSWORD__SUCCESS",
    FORGOTPASSWORD_ERROR: "FORGOTPASSWORD_ERROR",
};