export const ImageUploadActionTypes = {
    IMAGE_UPLOAD: 'IMAGE_UPLOAD',
    IMAGE_UPLOAD_LOADER: 'IMAGE_UPLOAD_LOADER',
    IMAGE_UPLOAD_SUCCESS: 'IMAGE_UPLOAD_SUCCESS',
    IMAGE_UPLOAD_ERROR: 'IMAGE_UPLOAD_ERROR',
    IMAGE_UPLOAD_RESET: 'IMAGE_UPLOAD_RESET',
  };