export const MoveInDetailActionTypes = {
    MOVE_IN_DETAIL: 'MOVE_IN_DETAIL',
    MOVE_IN_DETAIL_LOADER: 'MOVE_IN_DETAIL_LOADER',
    MOVE_IN_DETAIL_SUCCESS: 'MOVE_IN_DETAIL_SUCCESS',
    MOVE_IN_DETAIL_ERROR: 'MOVE_IN_DETAIL_ERROR',
    MOVE_IN_DETAIL_RESET: 'MOVE_IN_DETAIL_RESET',
  };