export const MoveOutListActionTypes = {
    MOVE_OUT_LIST: 'MOVE_OUT_LIST',
    MOVE_OUT_LIST_LOADER: 'MOVE_OUT_LIST_LOADER',
    MOVE_OUT_LIST_SUCCESS: 'MOVE_OUT_LIST_SUCCESS',
    MOVE_OUT_LIST_ERROR: 'MOVE_OUT_LIST_ERROR',
  };