export const MoveOutRequestCancelActionTypes = {
    MOVE_OUT_REQUEST_CANCEL: 'MOVE_OUT_REQUEST_CANCEL',
    MOVE_OUT_REQUEST_CANCEL_LOADER: 'MOVE_OUT_REQUEST_CANCEL_LOADER',
    MOVE_OUT_REQUEST_CANCEL_SUCCESS: 'MOVE_OUT_REQUEST_CANCEL_SUCCESS',
    MOVE_OUT_REQUEST_CANCEL_ERROR: 'MOVE_OUT_REQUEST_CANCEL_ERROR',
  };