export const MoveInListActionTypes = {
    MOVE_IN_LIST: 'MOVE_IN_LIST',
    MOVE_IN_LIST_LOADER: 'MOVE_IN_LIST_LOADER',
    MOVE_IN_LIST_SUCCESS: 'MOVE_IN_LIST_SUCCESS',
    MOVE_IN_LIST_ERROR: 'MOVE_IN_LIST_ERROR',
  };