export const MoveInRequestCancelActionTypes = {
    MOVE_IN_REQUEST_CANCEL: 'MOVE_IN_REQUEST_CANCEL',
    MOVE_IN_REQUEST_CANCEL_LOADER: 'MOVE_IN_REQUEST_CANCEL_LOADER',
    MOVE_IN_REQUEST_CANCEL_SUCCESS: 'MOVE_IN_REQUEST_CANCEL_SUCCESS',
    MOVE_IN_REQUEST_CANCEL_ERROR: 'MOVE_IN_REQUEST_CANCEL_ERROR',
  };