export const MyMoveInListActionTypes = {
    MY_MOVE_IN_LIST: 'MY_MOVE_IN_LIST',
    MY_MOVE_IN_LIST_LOADER: 'MY_MOVE_IN_LIST_LOADER',
    MY_MOVE_IN_LIST_SUCCESS: 'MY_MOVE_IN_LIST_SUCCESS',
    MY_MOVE_IN_LIST_ERROR: 'MY_MOVE_IN_LIST_ERROR',
  };