export const MyPropertyDetailsActionTypes = {
  MY_PROPERTY_DETAILS: 'MY_PROPERTY_DETAILS',
  MY_PROPERTY_DETAILS_LOADER: 'MY_PROPERTY_DETAILS_LOADER',
  MY_PROPERTY_DETAILS_SUCCESS: 'MY_PROPERTY_DETAILS_SUCCESS',
  MY_PROPERTY_DETAILS_ERROR: 'MY_PROPERTY_DETAILS_ERROR',
  };