export const NewPasswordActionTypes = {
  NEW_PASSWORD: 'NEW_PASSWORD',
  NEW_PASSWORD_LOADER: 'NEW_PASSWORD_LOADER',
  NEW_PASSWORD_SUCCESS: 'NEW_PASSWORD_SUCCESS',
  NEW_PASSWORD_ERROR: 'NEW_PASSWORD_ERROR',
};
