export const NotificationCountActionTypes = {
  NOTIFICATION_COUNT: 'NOTIFICATION_COUNT',
  NOTIFICATION_COUNT_LOADER: 'NOTIFICATION_COUNT_LOADER',
  NOTIFICATION_COUNT_SUCCESS: 'NOTIFICATION_COUNT_SUCCESS',
  NOTIFICATION_COUNT_ERROR: 'NOTIFICATION_COUNT_ERROR',
  };