export const OwnerCreateActionTypes = {
    OWNER_CREATE: 'OWNER_CREATE',
    OWNER_CREATE_LOADER: 'OWNER_CREATE_LOADER',
    OWNER_CREATE_SUCCESS: 'OWNER_CREATE_SUCCESS',
    OWNER_CREATE_ERROR: 'OWNER_CREATE_ERROR',
    OWNER_CREATE_RESET: 'OWNER_CREATE_RESET',
  };