export const OwnerUpdateActionTypes = {
    OWNER_UPDATE: 'OWNER_UPDATE',
    OWNER_UPDATE_LOADER: 'OWNER_UPDATE_LOADER',
    OWNER_UPDATE_SUCCESS: 'OWNER_UPDATE_SUCCESS',
    OWNER_UPDATE_ERROR: 'OWNER_UPDATE_ERROR',
    OWNER_UPDATE_RESET: 'OWNER_UPDATE_RESET',
  };