export const PermanentAddressTypes = {
    PERM_ADDRESS: 'PERM_ADDRESS',
    PERM_ADDRESS_LOADER: 'PERM_ADDRESS_LOADER',
    PERM_ADDRESS_SUCCESS: 'PERM_ADDRESS_SUCCESS',
    PERM_ADDRESS_ERROR: 'PERM_ADDRESS_ERROR',
  };