export const RegistrationActionTypes = {
  REGISTRATION: 'REGISTRATION',
  REGISTRATION_LOADER: 'REGISTRATION_LOADER',
  REGISTRATION_SUCCESS: 'REGISTRATION_SUCCESS',
  REGISTRATION_ERROR: 'REGISTRATION_ERROR',
};
