export const RegistrationOTPActionTypes = {
    REGISTRATION_OTP: "REGISTRATION_OTP",
    REGISTRATION_OTP_LOADER: "REGISTRATION_OTP_LOADER",
    REGISTRATION_OTP_SUCCESS: "REGISTRATION_OTP_SUCCESS",
    REGISTRATION_OTP_ERROR: "REGISTRATION_OTP_ERROR",
};