export const RenewalRequestCancelActionTypes = {
    RENEWAL_REQUEST_CANCEL: 'RENEWAL_REQUEST_CANCEL',
    RENEWAL_REQUEST_CANCEL_LOADER: 'RENEWAL_REQUEST_CANCEL_LOADER',
    RENEWAL_REQUEST_CANCEL_SUCCESS: 'RENEWAL_REQUEST_CANCEL_SUCCESS',
    RENEWAL_REQUEST_CANCEL_ERROR: 'RENEWAL_REQUEST_CANCEL_ERROR',
    RENEWAL_REQUEST_CANCEL_RESET: 'RENEWAL_REQUEST_CANCEL_RESET',
  };