export const RestrictionServiceActionTypes = {
  RESTRICTION_SERVICE: 'RESTRICTION_SERVICE',
  RESTRICTION_SERVICE_LOADER: 'RESTRICTION_SERVICE_LOADER',
  RESTRICTION_SERVICE_SUCCESS: 'RESTRICTION_SERVICE_SUCCESS',
  RESTRICTION_SERVICE_ERROR: 'RESTRICTION_SERVICE_ERROR',
};
