export const SearchItemsActionTypes = {
  SEARCH_ITEMS: 'SEARCH_ITEMS',
  SEARCH_ITEMS_LOADER: 'SEARCH_ITEMS_LOADER',
  SEARCH_ITEMS_SUCCESS: 'SEARCH_ITEMS_SUCCESS',
  SEARCH_ITEMS_ERROR: 'SEARCH_ITEMS_ERROR',
};
