export const ServiceRequestUnitActionTypes = {
  SERVICE_REQUEST_UNIT: 'SERVICE_REQUEST_UNIT',
  SERVICE_REQUEST_UNIT_LOADER: 'SERVICE_REQUEST_UNIT_LOADER',
  SERVICE_REQUEST_UNIT_SUCCESS: 'SERVICE_REQUEST_UNIT_SUCCESS',
  SERVICE_REQUEST_UNIT_ERROR: 'SERVICE_REQUEST_UNIT_ERROR',
  };