export const ServiceRequestCommunityActionTypes = {
  SERVICE_REQUEST_COMMUNITY: 'SERVICE_REQUEST_COMMUNITY',
  SERVICE_REQUEST_COMMUNITY_LOADER: 'SERVICE_REQUEST_COMMUNITY_LOADER',
  SERVICE_REQUEST_COMMUNITY_SUCCESS: 'SERVICE_REQUEST_COMMUNITY_SUCCESS',
  SERVICE_REQUEST_COMMUNITY_ERROR: 'SERVICE_REQUEST_COMMUNITY_ERROR',
  };