export const TenantRenewalCreateActionTypes = {
    TENANT_RENEWAL_CREATE: 'TENANT_RENEWAL_CREATE',
    TENANT_RENEWAL_CREATE_LOADER: 'TENANT_RENEWAL_CREATE_LOADER',
    TENANT_RENEWAL_CREATE_SUCCESS: 'TENANT_RENEWAL_CREATE_SUCCESS',
    TENANT_RENEWAL_CREATE_ERROR: 'TENANT_RENEWAL_CREATE_ERROR',
    TENANT_RENEWAL_CREATE_RESET: 'TENANT_RENEWAL_CREATE_RESET',
  };