export const TenantUpdateActionTypes = {
    TENANT_UPDATE: 'TENANT_UPDATE',
    TENANT_UPDATE_LOADER: 'TENANT_UPDATE_LOADER',
    TENANT_UPDATE_SUCCESS: 'TENANT_UPDATE_SUCCESS',
    TENANT_UPDATE_ERROR: 'TENANT_UPDATE_ERROR',
    TENANT_UPDATE_RESET: 'TENANT_UPDATE_RESET',
  };