export const TenantCreateActionTypes = {
  TENANT_CREATE: 'TENANT_CREATE',
  TENANT_CREATE_LOADER: 'TENANT_CREATE_LOADER',
  TENANT_CREATE_SUCCESS: 'TENANT_CREATE_SUCCESS',
  TENANT_CREATE_ERROR: 'TENANT_CREATE_ERROR',
  TENANT_CREATE_RESET: 'TENANT_CREATE_RESET',
};
