export const UnitOwnerCreateActionTypes = {
    UNIT_OWNER_CREATE: 'UNIT_OWNER_CREATE',
    UNIT_OWNER_CREATE_LOADER: 'UNIT_OWNER_CREATE_LOADER',
    UNIT_OWNER_CREATE_SUCCESS: 'UNIT_OWNER_CREATE_SUCCESS',
    UNIT_OWNER_CREATE_ERROR: 'UNIT_OWNER_CREATE_ERROR',
    UNIT_OWNER_CREATE_RESET: 'UNIT_OWNER_CREATE_RESET',
  };