export const UnitOwnerRenewalCreateActionTypes = {
    UNIT_OWNER_RENEWAL_CREATE: 'UNIT_OWNER_RENEWAL_CREATE',
    UNIT_OWNER_RENEWAL_CREATE_LOADER: 'UNIT_OWNER_RENEWAL_CREATE_LOADER',
    UNIT_OWNER_RENEWAL_CREATE_SUCCESS: 'UNIT_OWNER_RENEWAL_CREATE_SUCCESS',
    UNIT_OWNER_RENEWAL_CREATE_ERROR: 'UNIT_OWNER_RENEWAL_CREATE_ERROR',
    UNIT_OWNER_RENEWAL_CREATE_RESET: 'UNIT_OWNER_RENEWAL_CREATE_RESET',
  };