export const UnitOwnerUpdateActionTypes = {
    UNIT_OWNER_UPDATE: 'UNIT_OWNER_UPDATE',
    UNIT_OWNER_UPDATE_LOADER: 'UNIT_OWNER_UPDATE_LOADER',
    UNIT_OWNER_UPDATE_SUCCESS: 'UNIT_OWNER_UPDATE_SUCCESS',
    UNIT_OWNER_UPDATE_ERROR: 'UNIT_OWNER_UPDATE_ERROR',
    UNIT_OWNER_UPDATE_RESET: 'UNIT_OWNER_UPDATE_RESET',
  };