export const UserProfileTypes = {
    USER_PROFILE: 'USER_PROFILE',
    USER_PROFILE_LOADER: 'USER_PROFILE_LOADER',
    USER_PROFILE_SUCCESS: 'USER_PROFILE_SUCCESS',
    USER_PROFILE_ERROR: 'USER_PROFILE_ERROR',
  };