import {all, fork} from 'redux-saga/effects';
import sample from './sample';
import login from './login';
import forgotPassword from './forgotPassword';
import forgotPasswordOtp from './forgotPasswordOtp';
import registration from './registration';
import registrationOTP from './registrationOtp';
import getCountries from './getCountry';
import getDialCode from './getDialCode';
import commonMasterCommunity from './commonMasterCommunity';
import commonCommunity from './commonCommunity';
import commonTower from './commonTower';
import commonUnit from './commonUnit';
import commonUnitDetail from './commonUnitDetail';
import tenantCreate from './tenantCreate';
import tenantUpdate from './tenantUpdate';
import companyCreate from './companyCreate';
import companyUpdate from './companyUpdate';
import ownerCreate from './ownerCreate';
import ownerUpdate from './ownerUpdate';
import userRoles from './userRoles';
import unitOwnerCreate from './unitOwnerCreate';
import unitOwnerUpdate from './unitOwnerUpdate';
import catalogueMasterCommunity from './catalogueMasterCommunity';
import catalogueCommunity from './catalogueCommunity';
import bookingSlots from './bookingSlots';
import amenitiesList from './amenitiesList';
import imageUpload from './imageUpload';
import moveInList from './moveInList';
import myMoveInList from './myMoveInList';
import moveInDetail from './moveInDetail';
import accessCardCommunity from './accessCardCommunity';
import AccessCardParkingBay from './accessCardParkingPay';
import moveInRequestCancel from './moveInRequestCancel';
import filterUnits from './filterUnits';
import catalogueWholeCommunity from './catalogueWholeCommunity';
import newPassword from './newPassword';
import moveOutList from './moveOutList';
import moveOutRequestCancel from './moveOutRequestCancel';
import serviceRequestUnitList from './serviceRequestUnitList';
import serviceRequestCommunityList from './serviceRequestCommunityList';
import promotions from './promotions';
import changePassGenOTP from './changePassGenOTP';
import resendOtp from './resendOtp';
import permanentAddress from './permanentAddress';
import userProfile from './userProfile';
import myPropertyDetails from './myPropertyDetails';
import defaultProperty from './defaultProperty';
import catalogueUnitCommunity from './catalogueUnitCommunity';
import tenantRenewalCreate from './tenantRenewalCreate';
import companyRenewalCreate from './companyRenewalCreate';
import unitOwnerRenewalCreate from './unitOwnerRenewalCreate';
import accountRenewalList from './accountRenewalList';
import renewalRequestCancel from './renewalRequestCancel';
import notificationCount from './notificationCount';
import restrictionService from './restrictionService';
import searchItems from './searchItems';

export default function* rootSaga() {
  yield all([fork(login)]);
  yield all([fork(forgotPassword)]);
  yield all([fork(forgotPasswordOtp)]);
  yield all([fork(sample)]);
  yield all([fork(registration)]);
  yield all([fork(registrationOTP)]);
  yield all([fork(getCountries)]);
  yield all([fork(getDialCode)]);
  yield all([fork(commonMasterCommunity)]);
  yield all([fork(commonCommunity)]);
  yield all([fork(commonTower)]);
  yield all([fork(commonUnit)]);
  yield all([fork(commonUnitDetail)]);
  yield all([fork(tenantCreate)]);
  yield all([fork(tenantUpdate)]);
  yield all([fork(companyCreate)]);
  yield all([fork(companyUpdate)]);
  yield all([fork(ownerCreate)]);
  yield all([fork(ownerUpdate)]);
  yield all([fork(userRoles)]);
  yield all([fork(unitOwnerCreate)]);
  yield all([fork(unitOwnerUpdate)]);
  yield all([fork(catalogueMasterCommunity)]);
  yield all([fork(catalogueCommunity)]);
  yield all([fork(bookingSlots)]);
  yield all([fork(amenitiesList)]);
  yield all([fork(imageUpload)]);
  yield all([fork(moveInList)]);
  yield all([fork(myMoveInList)]);
  yield all([fork(moveInDetail)]);
  yield all([fork(accessCardCommunity)]);
  yield all([fork(AccessCardParkingBay)]);
  yield all([fork(moveInRequestCancel)]);
  yield all([fork(filterUnits)]);
  yield all([fork(catalogueWholeCommunity)]);
  yield all([fork(newPassword)]);
  yield all([fork(serviceRequestUnitList)]);
  yield all([fork(serviceRequestCommunityList)]);
  yield all([fork(moveOutList)]);
  yield all([fork(moveOutRequestCancel)]);
  yield all([fork(promotions)]);
  yield all([fork(changePassGenOTP)]);
  yield all([fork(resendOtp)]);
  yield all([fork(permanentAddress)]);
  yield all([fork(userProfile)]);
  yield all([fork(myPropertyDetails)]);
  yield all([fork(defaultProperty)]);
  yield all([fork(catalogueUnitCommunity)]);
  yield all([fork(tenantRenewalCreate)]);
  yield all([fork(companyRenewalCreate)]);
  yield all([fork(unitOwnerRenewalCreate)]);
  yield all([fork(accountRenewalList)]);
  yield all([fork(renewalRequestCancel)]);
  yield all([fork(notificationCount)]);
  yield all([fork(restrictionService)]);
  yield all([fork(searchItems)]);
}
