export type ThemeAccessCard = {
    backgroundColor: string,
    menuBackground: string,
    cardBackground: string,
    cardBackgroundEdit: string,
    cardBorder: string,
    popupOuter: string,
    popupBackground: string,
    popupButton: string,
    lineBorder: string,
    activeBtnText: string,
    noteBackground: string,
    linkColor: string,
    primaryColor: string,
    primaryColorEdit: string,
    secondaryColor: string,
    secondaryColorEdit: string,
    activatedColor: string,
    progressColor: string,
    buttonColor: string,
    progressLight: string,
    transparent: string,
    dottedLine: string,
    popupBorderColor:string,
    activeButtonColor :string,
    cardValidationError :string
}