import {ThemeButton} from './IThemeButton';
import {ThemeCaptcha} from './IThemeCaptcha';
import {ThemeDropdown} from './IThemeDropdown';
import {ThemeText} from './IThemeText';
import {ThemeTextInput} from './IThemeTextInput';
import {ThemeRadioButton} from './IThemeRadioButton';
import {ThemeImageButton} from './IThemeImageButton';
import {ThemeSeparator} from './IThemeSeparator';
import {ThemeBookingSlots} from './IThemeBookingSlots';
import {ThemeAmenitiesList} from './IThemeAmenitiesList';
import {ThemeSwitchButton} from './IThemeSwitchButton';
import {ThemeTab} from './IThemeTab';
import {ThemeHHOCompanyHeader} from './IThemeHHOCompanyHeader';
import {ThemeTextInputUnderline} from './IThemeTextInputUnderline';
import {ThemeAddFile} from './IThemeAddFile';
import {ThemeBottomSheet} from './IThemeBottomSheet';
import {ThemeButtonBack} from './IThemeButtonBack';
import {ThemeMoveInRegisterOption} from './IThemeMoveInRegisterOption';
import {ThemeTableCell} from './IThemeTableCell';
import {ThemeSwitch} from './IThemeSwitch';
import {ThemeCatalogueText} from './IThemeCatalogueText';
import {ThemeAddressText} from './IThemeCatalogueAddressText';
import {ThemeCommunityHeaderText} from './IThemeCatalogueCommunityHeaderText';
import {ThemeCommunityText} from './IThemeCatalogueCommunity';
import {ThemeApartmentText} from './IThemeCatalogueCommunityApartment';
import {ThemeCarosuel} from './IThemeCarosuel';
import {ThemeMenuBotton} from './IThemeMenuButton';
import {ThemeTextInputOutline} from './IThemeTextInputOutline';
import {ThemeSwitchSelector} from './IThemeSwitchSelector';
import {ThemeAmenitiesSummery} from './IThemeAmenitiesSummery';
import {ThemeAmenitiesSuccess} from './IThemeAmenitiesSuccess';
import {ThemeView} from './IThemeView';
import { ThemeAccessCard } from './IThemeAccessCard';
import {ThemeLineSeparator} from './IThemeLineSeparator'
import {ThemeAddedFile} from './IThemeAddedFile';
import {ThemePropertyList} from './IThemePropertyList';
import {ThemeServiceRequest} from './IThemeServiceRequest';
import {ThemeMoveOut} from './IThemeMoveOut'
import {ThemeDashboard} from './IThemeDashboard'
import { ThemeFileBrowser } from './IThemeFileBrowser';
import { ThemeCheckBox } from './IThemeCheckBox';
import { ThemeLogin } from './IThemeLogin';
import { ThemeAlert } from './IThemeAlert';
import { ThemeBuying } from './IThemeBuying';
import { ThemeMoveInHeader } from './IThemeMoveInHeader';
import { ThemeDocumentRequired } from './IThemeDocumentRequired';
import { ThemeMoveInSuccessPopup } from './IThemeMoveInSuccessPopup';
import { ThemeMoveInRequestItem } from './IThemeMoveInRequestItem';
import { ThemeMoveOutRequestItem } from './IThemeMoveOutRequestItem';


export type ThemeTemplate = {
  themeColor: string;
  button: ThemeButton;
  text: ThemeText;
  textInput: ThemeTextInput;
  textInputUnderline: ThemeTextInputUnderline;
  dropdown: ThemeDropdown;
  captcha: ThemeCaptcha;
  radioButton: ThemeRadioButton;
  imageButton: ThemeImageButton;
  separator: ThemeSeparator;
  bookingSlots: ThemeBookingSlots;
  amenitiesList: ThemeAmenitiesList;
  switchButton: ThemeSwitchButton;
  tab: ThemeTab;
  hhoCompanyHeader: ThemeHHOCompanyHeader;
  moveInHeader: ThemeMoveInHeader;
  addFile: ThemeAddFile;
  addedFile: ThemeAddedFile;
  bottomSheet: ThemeBottomSheet;
  buttonBack: ThemeButtonBack;
  registerMoveInOption: ThemeMoveInRegisterOption;
  tableCell: ThemeTableCell;
  switch: ThemeSwitch;
  catalogueText: ThemeCatalogueText;
  addressText: ThemeAddressText;
  communityHeaderText: ThemeCommunityHeaderText;
  communityText: ThemeCommunityText;
  communityApartmentText: ThemeApartmentText;
  carosuel: ThemeCarosuel;
  menuButton: ThemeMenuBotton;
  textInputOutline: ThemeTextInputOutline;
  switchSelector: ThemeSwitchSelector;
  amenitiesSummery: ThemeAmenitiesSummery;
  amenitiesSuccess: ThemeAmenitiesSuccess;
  view: ThemeView;
  accessCard: ThemeAccessCard;
  propertyList: ThemePropertyList;
  serviceRequest: ThemeServiceRequest;
  lineSeparator:ThemeLineSeparator;
  moveOut:ThemeMoveOut;
  dashboard:ThemeDashboard;
  fileBrowser: ThemeFileBrowser;
  checkBox:ThemeCheckBox;
  loginTheme :ThemeLogin;
  alert: ThemeAlert;
  documentRequired: ThemeDocumentRequired;
  buying: ThemeBuying;
  moveInSuccess: ThemeMoveInSuccessPopup;
  moveInRequestItem: ThemeMoveInRequestItem;
  moveOutRequestItem: ThemeMoveOutRequestItem
};
